name: CI Pipeline

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Node.js 20
      uses: actions/setup-node@v4
      with:
        node-node: 20
        cache: 'npm'

    - name: Instalar Dependências
      run: npm ci || npm install

    - name: Validar Compilação (Build)
      run: npm run build