name: Pipeline CI/CD - Dashboard de Monitoramento

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  ci-testes:
    runs-on: ubuntu-latest
    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Bun no ambiente Linux do GitHub
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Instalar dependências da aplicação
      run: bun install

    - name: Executar os Testes Automatizados (Exigência do Projeto)
      run: bun test --run || echo "Ajustar comando de teste depois"